### ISSUE TITLE
Ошибочка

### ISSUE THREAD

**Issue by VadyChel** [tuxlabore/flasher-rewrite#9]
![Screenshot_99](https://user-images.githubusercontent.com/67959852/103567948-5702de00-4ecd-11eb-8b9b-2c4e750ad8a4.png)
Ничего не смущает? :coolstoryBob:

**Comment by tuxlabore** [comment]
Fixed in [latest commit](https://github.com/tuxlabore/flasher-rewrite/commit/149abd9e51309a73792268d62d1613c7cb75c025)
